/*
 * Footstep Power Generation & Energy Harvesting System
 * 
 * Description:
 * Reads rectified DC voltage generated by a piezoelectric array,
 * calculates step count and live voltage, and displays parameters
 * on a 16x2 I2C LCD screen while driving a status LED indicator.
 */

#include <Wire.h>
#include <LiquidCrystal_I2C.h>

// Set LCD address to 0x27 (or 0x3F) for 16x2 display
LiquidCrystal_I2C lcd(0x27, 16, 2);

// Pin Definitions
const int piezoPin = A0;      // Analog input from piezo bridge rectifier & capacitor filter
const int ledPin = 13;        // Status LED / Transistor control output

// Variables
int stepCount = 0;            // Total step counter
float voltage = 0.0;          // Calculated DC voltage (0.0V - 5.0V)
const float threshold = 0.2;  // Voltage detection threshold in Volts

void setup() {
  // Initialize digital pin
  pinMode(ledPin, OUTPUT);
  digitalWrite(ledPin, LOW);
  
  // Initialize I2C LCD
  lcd.init();
  lcd.backlight();
  
  // Boot screen display
  lcd.setCursor(0, 0);
  lcd.print("FOOTSTEP POWER");
  lcd.setCursor(0, 1);
  lcd.print("GENERATOR MODEL");
  delay(2000);
  lcd.clear();
}

void loop() {
  // Read analog value (0 - 1023)
  int rawValue = analogRead(piezoPin);
  
  // Convert raw analog reading to voltage
  voltage = (rawValue * 5.0) / 1023.0;

  // Check if generated voltage exceeds threshold
  if (voltage > threshold) { 
    stepCount++;
    
    // Pulse status LED
    digitalWrite(ledPin, HIGH);
    delay(150);
    digitalWrite(ledPin, LOW);

    // Update LCD Screen
    lcd.setCursor(0, 0);
    lcd.print("Steps: ");
    lcd.print(stepCount);
    lcd.print("    "); // Clear residual characters

    lcd.setCursor(0, 1);
    lcd.print("Volt: ");
    lcd.print(voltage, 2);
    lcd.print("V   ");

    // Debounce delay to prevent double counting
    delay(300); 
  }
}
